name: deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t petmmunity-nest .
      - name: taging
        run: docker tag petmmunity-nest:latest qwe6293/petmmunity-nest:latest
      - name: Push to Dockerhub
        run: docker push qwe6293/petmmunity-nest:latest
      # - name: execute remote ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_SSH_HOST }}
      #     username: ${{ secrets.REMOTE_SSH_USERNAME }}
      #     key: ${{ secrets.REMOTE_SSH_KEY }}
      #     port: ${{ secrets.REMOTE_SSH_PORT }}
      #     script: |
      #       pwd
      #       sudo docker pull qwe6293/petmmunity-nest:latest
      #       sudo docker rm -f petmmunity-nest-container
      #       sudo docker run -d -p 3001:3001 --name petmmunity-nest-container qwe6293/nest-container
